### ISSUE TITLE
Изменение статуса пользователя после перехода по ссылке на почте

### ISSUE THREAD

**Issue by Novik-Artem** [Orange-hanter/AnriProject#31]
При переходе по ссылке на почте, которая приходит после геристрации, появляется ошибка 404.
![error](https://github.com/Orange-hanter/AnriProject/assets/81442713/44ba3857-dc58-4c49-9eb0-b4ac753eb7c8)

 Я поменял тип запроса с get на post и по ulr ссылки отправлял пост запрос, но ничего не изменилось. Пока не могу понять, почему после смены типа запроса не решилась проблема.
![1](https://github.com/Orange-hanter/AnriProject/assets/81442713/8897a797-4110-4f34-b6a5-727189d16214)
![2](https://github.com/Orange-hanter/AnriProject/assets/81442713/d1a80f03-ac46-4d51-990b-f68d4511f793)

Сейчас пока меняю статус пользователя через админку, такой способ отрабатывает корректно, приходят токены.

**Comment by Orange-hanter** [comment]
Задача решена. Отправляем с письма get запрос на клиент а он уже перенаправляет на сервер в post формате
