### ISSUE TITLE
потенциальная ошибка в свагере

### ISSUE THREAD

**Issue by Novik-Artem** [Orange-hanter/AnriProject#32]
обратил внимание, что response не соответствует описанию
![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/abbc6c7f-61b3-4acc-8600-9877a7ec87b1)
 в барузере это подтверждается
![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/b5b2974d-c2ad-4714-a6e9-02feeeb5ea47)
уточните, правильно ли работает verify, и что он должен возвращать?

**Comment by 132dannys** [comment]
@Novik-Artem а что в запросе?

**Comment by Orange-hanter** [comment]
Собственно, проведя инвестигейт, обнаружил момент.
Дока автоматически сгенерированна из джозера, а точнее его зависимости simpkle_jwt
Соответственно все вопросы к авторам библиотеки, что очень печально.

Нам нужно определить внутренний стек, как что работает. Я рассписал всё это в сообщении дискорда.
Пока что закрывать не стану этот тред, пускай повисит до полного решения вопроса

**Comment by Orange-hanter** [comment]
на лицо ряд моментов которых свагер не показывает
https://djoser.readthedocs.io/en/latest/jwt_endpoints.html
данные методы происходят из этой документации, соответственно там находится актуальная информация
