### ISSUE TITLE
[ОШИБКА] | post запрос в carts

### ISSUE THREAD

**Issue by Novik-Artem** [Orange-hanter/AnriProject#37]
# Описание проблемы
при отправки товара в корзину `/api/v1/carts` ловлю проблему, возвращается ошибка `500`
в запрос передаются все необходимые поля, согласно свагеру(картинка ниже)

![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/8a258f44-09bd-4f03-8ad8-c93f02d4bdec)

в response запроса приходит ошибка 500 следующего содержания(картинка ниже)

![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/ae0251fd-bb29-4444-be9e-2a6b9e13d099)

## суть проблемы:
товары не отправляются в корзину на бэк, прошу обратить внимание

**Comment by 132dannys** [comment]
@Novik-Artem корзина привязана к юзеру, юзер должен быть авторизован или на стороне клиента должна выполняться работа по созданию анонимного юзера.

**Comment by 132dannys** [comment]
> @132dannys с авторизацией есть проблема, смотри #32 
> 
> Этот момент является блокером для закрытия на фронте авторизации

А как корзина связана с проверкой jwt токена?

**Comment by Orange-hanter** [comment]
Как итог, ошибка растёт из-за не работающей в полной мере системы авторизации. С исправлением её данная программа исчезает
