### ISSUE TITLE
Добавление товаров в корзину и отрисовка товаров в корзине

### ISSUE THREAD

**Issue by Novik-Artem** [Orange-hanter/AnriProject#42]
# Работаю над расширением функционала корзины

А именно над возможностью добавления товаров в корзину и дальнейшей их отрисовки пользователям.
Использую следующие эндпоинты:

* для получения товаров в корзине ( [картинка ](https://github.com/Orange-hanter/AnriProject/assets/81442713/a85b2fad-3c16-40a6-9cea-02fe810808f5))
`GET: /api/v1/carts`

* для добавления товара в корзину( [картинка ](https://github.com/Orange-hanter/AnriProject/assets/81442713/3e7ba9fd-5aff-443c-b0ac-1fcaf9a46308))
`POST: /api/v1/carts`

Для этого эндпоинта я передаю все требуемые поля: product - id товара, quantity - кол-во товара(картинка ниже)

![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/223c84fd-50f2-4ce1-81b5-ff6676a81c77)

## Суть проблемы
Два этих запроса возвращают статус 500 со следующим содержанием:

* запрос на получение товаров в корзине:

![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/927c9d68-4386-44fb-acff-6c757218658a)

* запрос на добавление товара в корзину:

![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/d3adb55f-67cd-489d-9544-dd3f90d12ea6)

Я помню, что мы обговаривали, что эта проблема связана с не до конца работающей авторизацией.
Сейчас она работает, в заголовках запросов передается токен, но проблема осталась

**Comment by Orange-hanter** [comment]
Что ты отправляешь в качестве id?

**Comment by 132dannys** [comment]
> Что ты отправляешь в качестве id?

Он ничего не отправляет и ничего и не должно отправлятся

**Comment by 132dannys** [comment]
Ты получаешь ошибку, которая гласит о том, что корзина привязана к юзеру. Юзер у нас может быть или ГОСТЬ, или уже ЗАРЕГЕСТРИРОВАННЫЙ. Если ты не пошел по одному из этих путей, то автоматически передается анонимный юзер(стандартное поведение джанго, тк анонимный юзер это встроенный юзер джанго). Ты должен передавать jwt токен, предварительно залогиневшись под ГОСТЕМ/ЗАРЕГИСТРИРОВАННЫМ пользователем

**Comment by 132dannys** [comment]
Еще ты прикрепил запрос, но не прикрепил хедеры, без этого не понятно отправляешь ли ты вообще jwt, если да, то я не знаю валидный он или нет.
Если все сделано правильно, то стоит смотреть на ошибку на стороне бэка

**Comment by Novik-Artem** [comment]
в качестве id я передаю uuid товара
также передаю в заголовках токен
* получение товаров
![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/d5988e93-744a-4505-a5b8-8d034e293b17)

* добавление товара
![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/f65ce96f-164e-485e-9e5a-17076a7751f0)

**Comment by 132dannys** [comment]
> в качестве id я передаю uuid товара
> 
> также передаю в заголовках токен
> 
> * получение товаров
> 
> ![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/d5988e93-744a-4505-a5b8-8d034e293b17)
> 
> 
> 
> * добавление товара
> 
> ![изображение](https://github.com/Orange-hanter/AnriProject/assets/81442713/f65ce96f-164e-485e-9e5a-17076a7751f0)
> 
> 

Ты не передаешь ничего в качестве id, потому что id это id юзера, а uuid это uuid товара. Более того ты и не должен отправлять id(кроме jwt). 
Не работает, потому что у тебя в хедерах перед jwt написано bearer, а у нас в настройках задано anri. Вот к вопросу надо ли оно, чтобы так работало..

**Comment by Novik-Artem** [comment]
Я понял, дома гляну, спасибо

**Comment by Novik-Artem** [comment]
поменял bearer на anri - все заработало
